### ISSUE TITLE
student cannot log in

### ISSUE THREAD

**Issue by AmalHany** [amrdraz/kodr#50]
philopateer.hakim@student.guc.edu.eg gets incorrect username or password even after I changed his password from the admin account twice :D
and when we choose forgot password we get identity not found.

**Comment by amrdraz** [comment]
can't you just delete him?

*Amr Draz*
*Teaching Assistant German University in Cairo (GUC)*

*Mobile:* (+2) (01001132292)   |   *LinkedIn: *[Profile
<http://eg.linkedin.com/in/amrdraz>] | *Skype: * (bing91)
