### ISSUE TITLE
Error in a challenge?

### ISSUE THREAD

**Issue by Kalernor** [amrdraz/kodr#51]
Hello Mr Amr Draz this is Youssef Hatem.
On my 40* challenge the problem was as follows: "We'll say that a positive integer, int n, divides itself if the number is divisible by every digit in it.

So for example 128 divides itself since 128 is divisible by 1,2 and 8. We'll say that no number is divisible by 0, so no number with 0 as a digit divides itself."
I wrote the code and tested it and made sure it was working and so was the case with all the tests when I submitted my answer, except for the last one where n=0. It said the expected output should have been 'The number divides itself' ??? D: Doesn't that contradict what the problem said above? I then submitted the exact same code again and this time it passed all tests.  If there is nothing wrong with the challenge then what was my mistake? I will provide my algorithm in case you would like to review it. Sorry for the long message just thought I would point it out :D
int m=n;
int i=n%10;
boolean x=false;
while(n!=0&&x!=true){
  if(i!=0){
  if(m%i!=0){
    System.out.println("The number does not divide itself");
    x=true;
  }else{
    n=n/10;
    i=n%10;}
  }else{
System.out.println("The number does not divide itself");
    x=true;
  }
if(n==0){
  System.out.println("The number divides itself");
}
}

**Comment by amrdraz** [comment]
The challenge generates random test cases.
Among them the case where the number is equal to zero was not tested.

In your algorithm If the number is zero then it does not go into the loop
and prints the number devides itself.

You need to add an additional if condition before the loop to account for
that test case.

And we need to write better tests for our problem
