### ISSUE TITLE
kodr.in issue

### ISSUE THREAD

**Issue by 842Mono** [amrdraz/kodr#52]
hi :D

kodr.in can't compile codes nor take submissions for about a week now! what's wrong with it?

**Comment by amrdraz** [comment]
it currently can (restarted the server)

however this is an ongoing bug that emerges from getting too many infinite
loop submissions.

will be fixed this weekend (busy with last week lab quizzes and quizzes and
assignment and correcting grades of previous quiz)

*Amr Draz*
*Teaching Assistant German University in Cairo (GUC)*

*Mobile:* (+2) (01001132292)   |   *LinkedIn: *[Profile
<http://eg.linkedin.com/in/amrdraz>] | *Skype: * (bing91)
