### ISSUE TITLE
Ko;dr Feedback

### ISSUE THREAD

**Issue by mohamedkhaledali** [amrdraz/kodr#53]
Dear amr;

Thank you for creating Ko;dr. I had a blast going through all the challenges in the arenas, with every challenge getting more difficult and becoming worth more experience. I felt a great sense of accomplishment once i completed a challenge, even more when i completed a hard one. The interface is easy to read and use, the hints help out a lot and the questions really urge you to think outside the box. I also love how the console is really well done, using bright vivid colors for the text and a dark background to offset the contrast and make it easy on the eyes to read the text. My only complaint would be that there weren't any more challenges for me to complete once i was done with the arenas! I had so much fun writing java code, and i learned a whole lot from it as well. I wish the project will keep expanding, offering more and more challenging arenas. One suggestion i have is creating challenges requiring a certain amount of exp. to unlock. this way creating a requirement will make the challenge more rewarding due to it being more demanding than normal challenges. In addition, more colorful badges being rewarded for completing certain arenas would be a nice motivation. 

Best of luck;
A GUC student

**Comment by amrdraz** [comment]
Thank you for the feedback

I did recently post some challenges
however it is the case that while grading I was unable to post more

your suggestions will be handled in #33 and a new issue was created in #54
